[package]
name = "build-pulse"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.39", features = ["derive"] }
env_logger = "0.11.8"
jenkins_api = "0.8.0"
log = "0.4.27"
maud = "0.27.0"
regex = "1.11.1"
serde = "1.0.219"
