jenkins_url = "https://jenkins-pmrs.cels.anl.gov"
project = "mpich-main-nightly"

# username = <OPTIONAL: your user>
# password = <OPTIONAL: your password>

database = "data.db"

[[tag]]
name = "gcc_emit"
desc = "GCC Compiler Warning"

# Matches messages of the following
# filepath:lineno:linecol?: error: <message>\n
#  <indented followups>\n
# <make error>
# https://www.gnu.org/prep/standards/html_node/Errors.html
pattern = '''(?m)^[a-zA-Z0-9_\-./ ]+:[0-9]+(:[0-9]+)?: error: .*(\n\s*.*)*?\nmake.*$'''
from = "Console"

[[tag]]
name = "configure_error"
desc = "./configure failure"

# Matches messages of the following
# configure: error: .*\n
# See `config.log' for more details
pattern = '''(?m)^configure: error: .*\nSee `config.log' for more details$'''
from = "Console"

[[tag]]
name = "jenkins_agent_offline"
desc = "Jenkins Build Agent went offline during the build"

pattern = '''(?m)^Agent went offline during the build$'''
from = "Console"
