jenkins_url = "https://jenkins-pmrs.cels.anl.gov"
project = "mpich-main-nightly"

timezone = -5 # in UTC-<hour> format

# username = <OPTIONAL: your user>
# password = <OPTIONAL: your password>

database = "data.db"

### FATAL TOOLING EMITS
### ----------------------------------------------------------------------
[[tag]]
name = "cc_emit"
desc = "CC Compiler Warning"

# Matches messages of the following
# <filepath>:<lineno>:<linecol?>: error: <message>\n
#  <indented followups>\n
# https://www.gnu.org/prep/standards/html_node/Errors.html
pattern = '''(?m)^[a-zA-Z0-9_\-\./ ]+([\.\-:][0-9]+){0,4}: error: .*(\n\s+.*)*(\n[a-zA-Z0-9_\-\./ ]+([\.\-:][0-9]+){0,4}: [a-z]+: .*(\n\s+.*)*)*$'''
from = "Console"
severity = "Error"

[[tag]]
name = "configure_error"
desc = "./configure failure"

# Matches messages of the following
# configure: error: <message>\n
# See `<log file>' for more details
pattern = '''(?m)^configure: error: .*$'''
from = "Console"
severity = "Error"

[[tag]]
name = "jenkins_agent_offline"
desc = "Jenkins Build Agent went offline during the build"

pattern = '''(?m)^Agent went offline during the build$'''
from = "Console"
severity = "Warning"

[[tag]]
name = "java_stack_trace"
desc = "Java Exception Stack Trace"

# Matches messages of the following example
# FATAL: java.io.IOException: Unexpected termination of the channel
# java.io.EOFException
# 	at java.base/java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2915)
# 	at java.base/java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:3410)
# 	at java.base/java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:954)
# 	at java.base/java.io.ObjectInputStream.<init>(ObjectInputStream.java:392)
# 	at hudson.remoting.ObjectInputStreamEx.<init>(ObjectInputStreamEx.java:50)
# 	at hudson.remoting.Command.readFrom(Command.java:142)
# 	at hudson.remoting.Command.readFrom(Command.java:128)
# 	at hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:35)
# 	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:61)
# Caused: java.io.IOException: Unexpected termination of the channel
# 	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:75)
# Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to pmrs-linux-240-01
# 		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1826)
# 		at hudson.remoting.Request.call(Request.java:199)
# 		at hudson.remoting.Channel.call(Channel.java:1041)
# 		at hudson.Launcher$RemoteLauncher.kill(Launcher.java:1147)
# 		at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:538)
# 		at hudson.model.Run.execute(Run.java:1894)
# 		at PluginClassLoader for matrix-project//hudson.matrix.MatrixRun.run(MatrixRun.java:153)
# 		at hudson.model.ResourceController.execute(ResourceController.java:101)
# 		at hudson.model.Executor.run(Executor.java:446)
# Caused: hudson.remoting.RequestAbortedException
# 	at hudson.remoting.Request.abort(Request.java:346)
# 	at hudson.remoting.Channel.terminate(Channel.java:1122)
# 	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:90)
pattern = '''(?m)^([a-zA-Z]+: .*\n([a-z]+\.)+[a-zA-Z]+(\n\s+.*)*)+$'''
from = "Console"
severity = "Warning"

[[tag]]
name = "mpi_abort"
desc = "Generic MPI failure conditions"

# Matches messages of the following
# Abort(<number>) on node <number>: <message>
# <function name>(<number>)\.*: <stack traces>\n
pattern = '''(?m)^Abort\([0-9]+\) on node [0-9]+: .*(\n[a-zA-Z_][a-zA-Z0-9_]+\([0-9]+\)\.*: .*)*$'''
from = "Console"
severity = "Error"

[[tag]]
name = "python_traceback"
desc = "Python Exception Traceback"

# Matches messages of the following example
# Traceback (most recent call last):
#   File "/builder_task.py", line 279, in do_one_task
#     raise RecoverableBuildException("test error")
# common.exceptions.BuildException
# https://stackoverflow.com/questions/53658695/how-to-match-the-whole-traceback-message-and-not-stop-early-using-regex
pattern = '''(?m)^Traceback \(most recent call last\):(?:\n.*)+?\n(.*?(?:Exception|Error):)\s*(.+)$'''
from = "Console"
severity = "Error"

[[tag]]
name = "ld_error"
desc = "Program can't find shared library"

# Matches messages of the following
# <program name>: error while loading shared libraries: <libraries>
pattern = '''(?m)^.+: error while loading shared libraries: .*$'''
from = "Console"
severity = "Error"

[[tag]]
name = "cpi_failed_assert"
desc = "Failed assertion from cpi"

# Matches messages of the following
# cpi: <filepath>:<line no>: <function signature>: Assertion `<exp' failed.
pattern = '''(?m)^cpi: [a-zA-Z0-9_\-\./ ]+([\.\-:][0-9]+){0,4}: .*: Assertion `.*' failed.$'''
from = "Console"
severity = "Error"

### PLATFORM TAGS
### ----------------------------------------------------------------------
[[tag]]
name = "bsd"
desc = "FreeBSD Build"

pattern = '''freebsd64'''
from = "RunName"
severity = "Metadata"

[[tag]]
name = "linux"
desc = "Linux Build"

pattern = '''(ubuntu([0-9]{1,2}.[0-9]{1,2})?)|(debian([0-9]+)?)|(centos([0-9]+)?)|(opensuse(-(leap)|(tumbleweed))?)'''
from = "RunName"
severity = "Metadata"

[[tag]]
name = "osx"
desc = "macOS Build"

pattern = '''osx'''
from = "RunName"
severity = "Metadata"

[[tag]]
name = "aarch64"
desc = "aarch64 Build"

pattern = '''aarch64'''
from = "RunName"
severity = "Metadata"

### TOOLCHAIN TAGS
### ----------------------------------------------------------------------
[[tag]]
name = "gnu"
desc = "gcc Build"

pattern = '''(gnu)|(gcc[0-9]*)'''
from = "RunName"
severity = "Metadata"

[[tag]]
name = "clang"
desc = "clang Build"

pattern = '''clang'''
from = "RunName"
severity = "Metadata"

[[tag]]
name = "intel"
desc = "Intel OneAPI Build"

pattern = '''intel(-oneapi)?'''
from = "RunName"
severity = "Metadata"

### BUILD NODE TAGS
### ----------------------------------------------------------------------
[[tag]]
name = "pmrs-freebsd64-240-01"
desc = "pmrs-freebsd64-240-01 Build Node"

pattern = '''(?m)^Building remotely on pmrs-freebsd64-240-01.*$'''
from = "Console"
severity = "Metadata"

[[tag]]
name = "pmrs-freebsd64-240-02"
desc = "pmrs-freebsd64-240-02 Build Node"

pattern = '''(?m)^Building remotely on pmrs-freebsd64-240-02.*$'''
from = "Console"
severity = "Metadata"

[[tag]]
name = "pmrs-gpu-240-01"
desc = "prms-gpu-240-01 Build Node"

pattern = '''(?m)^Building remotely on pmrs-gpu-240-01.*$'''
from = "Console"
severity = "Metadata"

[[tag]]
name = "pmrs-gpu-240-02"
desc = "prms-gpu-240-02 Build Node"

pattern = '''(?m)^Building remotely on pmrs-gpu-240-02.*$'''
from = "Console"
severity = "Metadata"

[[tag]]
name = "pmrs-linux-240-01"
desc = "prms-linux-240-01 Build Node"

pattern = '''(?m)^Building remotely on pmrs-linux-240-01.*$'''
from = "Console"
severity = "Metadata"

[[tag]]
name = "pmrs-linux-240-02"
desc = "prms-linux-240-02 Build Node"

pattern = '''(?m)^Building remotely on pmrs-linux-240-02.*$'''
from = "Console"
severity = "Metadata"

[[tag]]
name = "pmrs-linux-240-03"
desc = "prms-linux-240-03 Build Node"

pattern = '''(?m)^Building remotely on pmrs-linux-240-03.*$'''
from = "Console"
severity = "Metadata"

[[tag]]
name = "pmrs-linux-240-04"
desc = "prms-linux-240-04 Build Node"

pattern = '''(?m)^Building remotely on pmrs-linux-240-04.*$'''
from = "Console"
severity = "Metadata"

[[tag]]
name = "pmrs-linux-240-05"
desc = "prms-linux-240-05 Build Node"

pattern = '''(?m)^Building remotely on pmrs-linux-240-05.*$'''
from = "Console"
severity = "Metadata"

[[tag]]
name = "pmrs-linux-240-06"
desc = "prms-linux-240-06 Build Node"

pattern = '''(?m)^Building remotely on pmrs-linux-240-06.*$'''
from = "Console"
severity = "Metadata"

[[tag]]
name = "pmrs-macos-240-01.cels.anl.gov"
desc = "prms-macos-240-01.cels.anl.gov Build Node"

pattern = '''(?m)^Building remotely on pmrs-macos-240-01.cels.anl.gov.*$'''
from = "Console"
severity = "Metadata"

[[tag]]
name = "softiron-1"
desc = "softiron-1 Build Node"

pattern = '''(?m)^Building remotely on softiron-1.*$'''
from = "Console"
severity = "Metadata"

[[tag]]
name = "softiron-2"
desc = "softiron-2 Build Node"

pattern = '''(?m)^Building remotely on softiron-2.*$'''
from = "Console"
severity = "Metadata"

[[tag]]
name = "tiger"
desc = "tiger Build Node"

pattern = '''(?m)^Building remotely on tiger \(xpmem\).*$'''
from = "Console"
severity = "Metadata"

[[tag]]
name = "tiger"
desc = "tiger Build Node"

pattern = '''(?m)^Building remotely on tiger.*$'''
from = "Console"
severity = "Metadata"

[[tag]]
name = "yuzu"
desc = "yuzu Build Node"

pattern = '''(?m)^Building remotely on yuzu \(xpmem\).*$'''
from = "Console"
severity = "Metadata"

[[tag]]
name = "built-in"
desc = "built-in Build Node"

pattern = '''(?m)^Building remotely on built-in node.*$'''
from = "Console"
severity = "Metadata"

[[tag]]
name = "aws"
desc = "aws Build Node"

pattern = '''(?m)^Building remotely on aws.*$'''
from = "Console"
severity = "Metadata"
